services:
  app:
    image: hello-front
    build: .
    ports:
      - 8000:80
  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app